=== alex-dr1/testWork/src/main/resources/xsd/securities.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="document">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rows">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="row" maxOccurs="unbounded" minOccurs="1">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="secid" use="required"/>
                                                        <xs:attribute type="xs:string" name="name" use="required"/>
                                                        <xs:attribute type="xs:string" name="regnumber" use="required"/>
                                                        <xs:attribute type="xs:string" name="emitent_title" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="id" fixed="securities"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alex-dr1/testWork/inbox/securitiesAFKS.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../src/main/resources/xsd/securities.xsd">
    <data id="securities">
        <rows>
            <row id="2699" secid="AFKS" name="АФК &quot;Система&quot; ПАО ао" regnumber="1-05-01669-A" emitent_title="ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО &quot;АКЦИОНЕРНАЯ ФИНАНСОВАЯ КОРПОРАЦИЯ &quot;СИСТЕМА&quot;" />
            <row id="411869597" secid="AKH1" name="Фьючерсный контракт AFKS-3.21" regnumber="" emitent_title="ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО &quot;АКЦИОНЕРНАЯ ФИНАНСОВАЯ КОРПОРАЦИЯ &quot;СИСТЕМА&quot;" />
            <row id="411184895" secid="AKZ0" name="Фьючерсный контракт AFKS-12.20" regnumber="" emitent_title="ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО &quot;АКЦИОНЕРНАЯ ФИНАНСОВАЯ КОРПОРАЦИЯ &quot;СИСТЕМА&quot;" />
            <row id="412506703" secid="AFKS_CLT" name="AFKS_CLT" regnumber="" emitent_title="ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО &quot;АКЦИОНЕРНАЯ ФИНАНСОВАЯ КОРПОРАЦИЯ &quot;СИСТЕМА&quot;" />
            <row id="412425327" secid="AKM1" name="Фьючерсный контракт AFKS-6.21" regnumber="" emitent_title="ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО &quot;АКЦИОНЕРНАЯ ФИНАНСОВАЯ КОРПОРАЦИЯ &quot;СИСТЕМА&quot;" />
            <row id="8070" secid="AFKS-2007" name="АФК &quot;Система&quot; ОАО ао" regnumber="1-04-01669-A" emitent_title="" />
            <row id="411184893" secid="AKU0" name="Фьючерсный контракт AFKS-9.20" regnumber="" emitent_title="ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО &quot;АКЦИОНЕРНАЯ ФИНАНСОВАЯ КОРПОРАЦИЯ &quot;СИСТЕМА&quot;" />
        </rows>
    </data>
</document>
